- hosts: all
  tasks: 
  - name: "Repo"
    yum_repository:
      name: "Docker"
      description: "Docker Repo"
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/"
      gpgcheck: "no"
  - name: "creating docker"
    package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present
  - name: "starting docker"
    service: 
      name: "docker"
      state: started
      enabled: yes
  - name: "python"
    command: "pip3 install docker"
  - name: "Folder creation"
    file:
      path: "/ansiblefile"
      state: directory
  - name: "copying files"
    copy:
      src: "my.html" 
      dest: "/var/www/html/index.html"
  - name: "creating OS"
    docker_container:
      name: "ansibleweb21"
      image: "httpd"
      state: started
      exposed_ports:
      - "80"
      ports:
      - "5490:80"
      volumes:
      - /home/:/usr/local/apache2/htdocs/
    
    
